# Generated by Django 5.0.6 on 2024-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown1', models.CharField(max_length=100)),
                ('dropdown2', models.CharField(max_length=100)),
                ('dropdown3', models.CharField(max_length=100)),
                ('dropdown4', models.CharField(max_length=100)),
            ],
        ),
    ]
